version: "3"

services:
  directus:
    image: directus/directus:9.22.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./extensions:/directus/extensions
      - ./uploads:/directus/uploads
    environment:
      KEY: "0fda9121-269d-44bd-91f2-4ff05be14b4b"
      SECRET: "86cb4a76-a4c6-4ce7-8181-b0445d95675c"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      #DB_FILENAME: "/directus/database/elb.db"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      CONTENT_SECURITY_POLICY_USE_DEFAULT: false
      CONTENT_SECURITY_POLICY_DIRECTIVES__DEFAULT_SRC: "array:'self'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "array:'self'" 
      CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC: "array:'self' data: blob: http://127.0.0.1:8055" # localhost:8055,127.0.0.1:8055
      CONTENT_SECURITY_POLICY_DIRECTIVES__OBJECT_SRC: "array:'none'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: "[]"
  
  website:
    image: directus/website:latest
    ports:
      - 4200:4200
    environment:
      - API_HOST=directus
      - API_PORT=8055
