version: "3"

services:
  directus:
    image: directus/directus:9.22.1
    ports:
      - 8055:$PORT
    volumes:
      - ./database:/directus/database
      - ./extensions:$EXTENSIONS_PATH
      - ./uploads:$STORAGE_LOCAL_ROOT
    environment:

      KEY: $KEY
      SECRET: $SECRET

      DB_CLIENT: $DB_CLIENT
      DB_FILENAME: "/directus/database/$DB_FILENAME"
      CORS_ENABLED: $CORS_ENABLED
      CORS_ORIGIN: $CORS_ORIGIN
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD

      CONTENT_SECURITY_POLICY_USE_DEFAULT: false
      CONTENT_SECURITY_POLICY_DIRECTIVES__DEFAULT_SRC: "array:'self'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "array:'self'" 
      CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC: "array:'self' data: blob: http://127.0.0.1:8055" # localhost:8055,127.0.0.1:8055
      CONTENT_SECURITY_POLICY_DIRECTIVES__OBJECT_SRC: "array:'none'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: "[]"
  
  website:
    image: directusdemo/angular:local
    ports:
      - 4200:4200
    environment:
      - API_HOST=directus
      - API_PORT=8055
